# Generated by Django 2.2.12 on 2020-05-08 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='short_name',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category', to_field='short_name'),
        ),
    ]
